italia/eudi-wallet-it-python

example/satosa/pyeudiw_backend.yaml
pyeudiw/tests/satosa/test_backend.py

Closes https://github.com/italia/eudi-wallet-it-python/issues/60

Storage settings, interface and operations

---

pyeudiw/jwk/schema.py
pyeudiw/openid4vp/schema.py
pyeudiw/sd_jwt/schema.py
pyeudiw/tests/satosa/test_backend.py

feat: add vp token schema

---

linting.sh
pyeudiw/satosa/backend.py
pyeudiw/storage/base_cache.py
pyeudiw/storage/db_engine.py
pyeudiw/storage/mongo_cache.py
pyeudiw/storage/mongo_storage.py
pyeudiw/tests/storage/test_db_engine.py
pyeudiw/tests/storage/test_mongo_storage.py
pyeudiw/tests/tools/test_qr_code.py
requirements-dev.txt

Html linter output manipulated in order to make it simple to reach the problem in the code.
Closes #46

feat: html linter

---

pyeudiw/federation/schema.py
pyeudiw/federation/trust_chain_builder.py
pyeudiw/federation/trust_chain_validator.py
pyeudiw/tests/federation/test_policy.py
pyeudiw/tests/federation/test_schema.py
pyeudiw/tests/federation/test_static_trust_chain_validator.py

Added test for federation package

---

.github/workflows/python-app.yml

added skip-duplicate-actions in the github action for pyton CI

ci removed duplicated jobs

---

example/satosa/integration_test/main.py
pyeudiw/tests/satosa/test_backend.py

test: user attributes

---

pyeudiw/satosa/backend.py

Modified exception handling. 
pyeudiw returns an error in Satosa_Saml2Spid and we would like to log it.

fix: modified exception handling

---

example/satosa/pyeudiw_backend.yaml
pyeudiw/openid4vp/direct_post_response.py
pyeudiw/satosa/backend.py
pyeudiw/tests/settings.py

Closes https://github.com/italia/eudi-wallet-it-python/issues/158

fix: added salt in the pairwised subject id - closes #158

---

pyeudiw/satosa/backend.py
pyeudiw/tests/satosa/test_backend.py

changed response for pre_request_endpoint. 
No need to generate qrcode on satosa backend.

feat: changed qrcode handling

---

example/satosa/integration_test/main.py
example/satosa/integration_test/settings.py

Set up DBEngine to use the container version of MongoDB.

fix: update integration test to use the containerized mongodb

---

.gitignore
README.md
docs/Makefile
docs/conf.py
docs/index.rst
docs/make.bat
pyeudiw/satosa/backend.py
pyeudiw/tests/satosa/test_backend.py
pyeudiw/tests/settings.py
requirements-dev.txt

This PR resolves the issue with redirect_endpoint function's name and add the support for html docs generated using Sphinx.

fix: renamed endpoint name and added Sphinx support

---

pyeudiw/sd_jwt/__init__.py
setup.py

this PR resolves the breaking change found in the last version of the python package cryptography.
It exceeds and closes https://github.com/italia/eudi-wallet-it-python/pull/235

fix: deps, cryptography breaking changes

---

docs/STORAGE.md

Update `STORAGE.md` file with references and a briefly introduction to the classes structure.
Closes #232

Docs storage

---

pyeudiw/satosa/default/openid4vp_backend.py

Add an intermediate status with code 202.
Closes #222

feat: add intermediate status

---

pyeudiw/satosa/default/openid4vp_backend.py

This pull request is a proposal for https://github.com/italia/eudi-wallet-it-python/issues/243
The data dictionary passed to the jinja template engine now includes the previously missing (key, value) pairs.

fix: added qr code info to jinja te

---

pyeudiw/satosa/default/openid4vp_backend.py
pyeudiw/tests/satosa/test_backend.py

Closes #109 by filtering out requests that have not been processed through any frontend

Feat: check for previous authn session

---

example/satosa/templates/qr_code.html

Fixed missing javascript polling for 202 status code

fix: qrcode polling for 202 accepted

---

pyeudiw/tests/tools/test_utils.py

this closes #286 
also see https://github.com/italia/eudi-wallet-it-python/issues/286#issuecomment-2431776419

fix: rm un-necessary test check

---

README.SATOSA.md
docs/STORAGE.md
docs/TRUST.md

This PR includes some missing docs, in particular:
- closes #289 
- closes #266

feat: docs

---

example/satosa/integration_test/README.md
example/satosa/integration_test/cross_device_integration_test.py
example/satosa/integration_test/requirements_test.txt
example/satosa/templates/qr_code.html

This pull request fixes #265 
This pull request added new python depedencies that are exclusive to the integration test
Moreover:
1. a minor issue was fixed, where the button "Vai al servizio" contained a non-working link.
2. added a README for the integration test that includes, among the other, documentation for the new dependencies

feat: expanded integration test

---

docs/STORAGE.md
example/satosa/integration_test/commons.py
pyeudiw/openid4vp/authorization_request.py
pyeudiw/openid4vp/schemas/flow.py
pyeudiw/openid4vp/utils.py
pyeudiw/satosa/default/openid4vp_backend.py
pyeudiw/satosa/default/response_handler.py
pyeudiw/storage/base_storage.py
pyeudiw/storage/db_engine.py
pyeudiw/storage/mongo_storage.py
pyeudiw/tests/openid4vp/authorization_request.py
pyeudiw/tests/satosa/test_backend.py
pyeudiw/tests/storage/test_db_engine.py
pyeudiw/tests/storage/test_mongo_storage.py

This pull request is a proposal solution for potential issues emerged in #268 .
This PR inserts the flow detection information in the session storage so that it can be fetched by the response handler.
The current approach, removed by the PR, relies on unconfirmed assumption on the user agent.

feat: review of remote flow detection

---

example/satosa/pyeudiw_backend.yaml
pyeudiw/satosa/default/request_handler.py

fix: minor fixes

---

example/satosa/pyeudiw_backend.yaml

fix: updated class reference

---

pyeudiw/tests/trust/handler/test_direct_trust_jar.py
pyeudiw/trust/handler/_direct_trust_jwk.py

fix: bug key name in endpoint

---

example/satosa/pyeudiw_backend.yaml
setup.py

this PR is required to get an human setup to work

fix: dependencies and config alignments

---

pyeudiw/satosa/default/request_handler.py
pyeudiw/tests/satosa/test_backend.py
pyeudiw/tests/trust/mock_trust_handler.py
pyeudiw/tests/trust/test_dynamic.py
pyeudiw/trust/dynamic.py
pyeudiw/trust/handler/interface.py
pyeudiw/trust/interface.py
pyeudiw/trust/model/trust_source.py

Fix Trust params handling

---

docs/TRUST.md

Custom trust handler docs

---

pyeudiw/openid4vp/authorization_response.py
pyeudiw/openid4vp/schemas/response.py
pyeudiw/satosa/default/openid4vp_backend.py
pyeudiw/satosa/default/response_handler.py
pyeudiw/storage/base_storage.py
pyeudiw/storage/db_engine.py
pyeudiw/storage/mongo_storage.py
pyeudiw/tests/satosa/test_backend.py

Authorization Error Response Flow

---

pyeudiw/jwt/helper.py
pyeudiw/jwt/jws_helper.py
pyeudiw/jwt/parse.py
pyeudiw/jwt/utils.py
pyeudiw/openid4vp/exceptions.py
pyeudiw/openid4vp/interface.py
pyeudiw/openid4vp/vp_sd_jwt_vc.py
pyeudiw/satosa/default/response_handler.py
pyeudiw/sd_jwt/exceptions.py
pyeudiw/sd_jwt/sd_jwt.py
pyeudiw/tests/satosa/test_backend.py
pyeudiw/trust/default/direct_trust_sd_jwt_vc.py

Better error handling jwt

---

pyeudiw/jwk/parse.py
pyeudiw/tests/jwk/test_parse.py
pyeudiw/tests/satosa/test_backend.py
pyeudiw/tests/trust/handler/test_direct_trust.py
pyeudiw/trust/handler/_direct_trust_jwk.py

This pull requests closes #343 
Currently missing an unit test akin to https://github.com/italia/eudi-wallet-it-python/blob/dev/pyeudiw/tests/jwk/test_parse.py

feat: parsing ec key from x5c claim

---

pyeudiw/satosa/schemas/ui.py
pyeudiw/satosa/utils/html_template.py
pyeudiw/tests/settings.py

Removed error HTML template

---

pyeudiw/tests/trust/handler/test_direct_trust_jar.py

Public Key Test DirectTrustJar

---

example/satosa/pyeudiw_backend.yaml
pyeudiw/jwk/parse.py
pyeudiw/jwt/helper.py
pyeudiw/jwt/jws_helper.py
pyeudiw/satosa/default/request_handler.py
pyeudiw/tests/satosa/test_backend.py
pyeudiw/tests/settings.py
pyeudiw/tests/trust/handler/test_x509.py
pyeudiw/trust/handler/x509.py

X5C chain RP relation

---

pyeudiw/federation/schemas/openid_credential_verifier.py
pyeudiw/openid4vp/authorization_request.py
pyeudiw/satosa/default/request_handler.py
pyeudiw/trust/dynamic.py
pyeudiw/trust/model/trust_source.py

fix: missing iss in request and removal of useless pydantic warning about deprecated params

---

example/satosa/pyeudiw_backend.yaml
pyeudiw/openid4vp/presentation_submission/__init__.py
pyeudiw/satosa/default/openid4vp_backend.py
pyeudiw/tests/openid4vp/test_presentation_submission.py
pyeudiw/tests/settings.py
pyeudiw/tests/trust/mock_trust_handler.py
pyeudiw/tests/trust/test_dynamic.py
pyeudiw/trust/model/trust_source.py

Fix for integration tests

---

example/satosa/pyeudiw_backend.yaml
pyeudiw/tests/settings.py
pyeudiw/tests/trust/handler/test_x509.py
pyeudiw/tests/x509/test_x509.py
pyeudiw/trust/handler/x509.py
pyeudiw/x509/verify.py

Check that the first key is properly configured

---

pyeudiw/openid4vp/authorization_response.py
pyeudiw/satosa/default/request_handler.py
pyeudiw/tests/openid4vp/test_authorization_response.py

This PR closes #415 and closes #413 by applying the proposed solutions

fix: handling of presentation sub in direct post

---

pyeudiw/jwk/parse.py
pyeudiw/openid4vp/vp_sd_jwt_vc.py
pyeudiw/tests/jwk/test_parse.py
pyeudiw/tests/openid4vp/test_vp_sd_jwt_vc.py
pyeudiw/tests/satosa/test_backend.py
pyeudiw/trust/handler/x509.py
pyeudiw/x509/verify.py

Invalid x5c store and status list fix

---

pyeudiw/openid4vp/authorization_response.py
pyeudiw/satosa/default/response_handler.py
pyeudiw/tests/openid4vp/test_authorization_response.py

direct_post.jwt could be not necessarly encrypted

---

pyeudiw/tests/settings.py
pyeudiw/tests/trust/handler/test_x509.py
pyeudiw/trust/handler/x509.py
pyeudiw/x509/verify.py

x509_san_uri removal

---

pyeudiw/tests/x509/test_x509.py
pyeudiw/x509/chain_builder.py

this PR has introduces few changes improving the gen_chain unit test function for the purpose to use it as example builder for the eid-wallet-it-docs

chore: small improvements in x509 example chain build, unit test

---

pyeudiw/jwt/jws_helper.py
pyeudiw/openid4vp/schemas/wallet_metadata.py
pyeudiw/satosa/default/request_handler.py
pyeudiw/tests/satosa/test_backend.py

Post request features

---

example/satosa/openid4vci_frontend.yaml
pyeudiw/satosa/backends/openid4vp/openid4vp.py
pyeudiw/trust/handler/federation.py

This PR fixes the .well-know paths for VP and VCI

Reachable .well-know paths

---

docs/OPENID4VCI-SATOSA-FRONTEND.md
integration_test/conf/openid4vci_frontend.yaml
pyeudiw/satosa/frontends/openid4vci/endpoints/base_credential_endpoint.py
pyeudiw/satosa/frontends/openid4vci/endpoints/pushed_authorization_request_endpoint.py
pyeudiw/satosa/frontends/openid4vci/endpoints/token_endpoint.py
pyeudiw/satosa/frontends/openid4vci/endpoints/vci_base_endpoint.py
pyeudiw/satosa/utils/validation.py
pyeudiw/tests/satosa/frontends/openid4vci/endpoints/test_pushed_authorization_request_endpoint.py
pyeudiw/tests/satosa/frontends/openid4vci/endpoints/test_token_endpoint.py
pyeudiw/tests/satosa/frontends/openid4vci/mock_openid4vci.py
pyeudiw/tests/satosa/utils/test_validation.py
setup.py

Optional wallet attestation

---

docs/OPENID4VCI-SATOSA-FRONTEND.md
docs/OPENID4VP-SATOSA-BACKEND.md
integration_test/conf/openid4vci_frontend.yaml
integration_test/conf/potential/wp2uc1/userdenies/pyeudiw_backend.yaml
integration_test/conf/pyeudiw_backend.yaml
integration_test/initializer/settings.py
pyeudiw/tests/satosa/backends/openid4vp/test_vp_mdoc_cbor.py
pyeudiw/tests/satosa/frontends/openid4vci/mock_openid4vci.py
pyeudiw/tests/settings.py
pyeudiw/tests/storage/test_mongo_cache.py
pyeudiw/tests/storage/test_mongo_storage.py

rev: MongoDB schema and collection naming review

---

docs/OPENID4VCI-SATOSA-FRONTEND.md
integration_test/conf/openid4vci_frontend.yaml
pyeudiw/satosa/frontends/openid4vci/endpoints/base_credential_endpoint.py
pyeudiw/satosa/frontends/openid4vci/endpoints/pushed_authorization_request_endpoint.py
pyeudiw/satosa/frontends/openid4vci/endpoints/token_endpoint.py
pyeudiw/satosa/frontends/openid4vci/endpoints/vci_base_endpoint.py
pyeudiw/satosa/schemas/metadata.py
pyeudiw/satosa/utils/validation.py
pyeudiw/tests/satosa/utils/test_validation.py

feat: openid4vci dpop_signing_alg_values_supported configuration

---

integration_test/conf/openid4vci_frontend.yaml
pyeudiw/jwt/jws_helper.py
pyeudiw/satosa/frontends/openid4vci/endpoints/pushed_authorization_request_endpoint.py
pyeudiw/satosa/frontends/openid4vci/endpoints/vci_base_endpoint.py

Optional signed request
