pyeudiw/satosa/backend.py, pyeudiw/storage/base_storage.py, pyeudiw/storage/db_engine.py, pyeudiw/storage/mongo_storage.py, pyeudiw/tests/satosa/test_backend.py, pyeudiw/tests/storage/test_db_engine.py, pyeudiw/tests/storage/test_mongo_storage.py
Session id in pre_request's output path as https://github.com/italia/eudi-wallet-it-docs/pull/87
=> feat: status endpoint

pyeudiw/satosa/backend.py, pyeudiw/sd_jwt/__init__.py, pyeudiw/tests/satosa/test_backend.py
Status endpoint checks if a request object exists.
If it exists, the `exp` field from the object is evaluated with the current timestamp.
Closes #139
=> Handle expired request

pyeudiw/oauth2/dpop/__init__.py, pyeudiw/openid4vp/schemas/wallet_instance_attestation.py, pyeudiw/satosa/backend.py, pyeudiw/satosa/dpop.py, pyeudiw/sd_jwt/__init__.py, pyeudiw/tests/oauth2/test_dpop.py, pyeudiw/tests/openid4vp/schemas/test_wallet_instance_attestation.py, pyeudiw/tests/settings.py
- Update WIA Pydantic Schema with latest specs
- Validate WIA Payload before use in DPoP Verifier
- [Warning only] Validate WIA Header 
- Fix logging in DPoP Verifier
Closes #141
=> feat: WIA Pydantic validation

pyeudiw/satosa/backend.py, pyeudiw/tests/satosa/test_backend.py, pyeudiw/tests/settings.py, pyeudiw/trust/__init__.py, pyeudiw/trust/trust_anchors.py
- fix: trust chain evaluation
improve error message and fix evaluation
- fix: safe access to user_attributes
fix access to `config` key using `get` function to avoid Invalid key error.
- fix: logging
add logger and logging warning call, as per TODO
- test: redirect endpoint test fixes and improvement
add additional testing call into redirect endpoint test, including a correct execution up to the redirect response
closes #146
=> Fix satosa backend tests

pyeudiw/jwk/schema.py
According to [RFC7517 section 4.4](https://datatracker.ietf.org/doc/html/rfc7517#section-4.4), `alg` is optional .
=> chore: remove TODO

pyeudiw/satosa/backend.py, pyeudiw/tests/satosa/test_backend.py
=> fix: add specific exception handling for VP token

pyeudiw/sd_jwt/__init__.py
This pull request is aimed at fixing #249 
Data structure of pyeudi sdk object is unchanged (still accepts only one JWK) but is traslated to a list of one element when invoking parent constructor.
=> fix: compatibility with sd-jwt-python v0.10.4

example/satosa/integration_test/settings.py, example/satosa/pyeudiw_backend.yaml, pyeudiw/tests/oauth2/test_dpop.py, pyeudiw/tests/openid4vp/schemas/test_wallet_instance_attestation.py, pyeudiw/tests/satosa/test_backend.py, pyeudiw/tests/settings.py
Wallet instance invocation used to rely on a custom scheme called `eudiw://`, but according to interoperability specs [OpenID4VC High Assurance Interoperability Profile with SD-JWT VC - draft 00](https://openid.net/specs/openid4vc-high-assurance-interoperability-profile-sd-jwt-vc-1_0-00.html), the scheme `haip://` should be preferred.
This pull requests proposes to fill this gap in default satosa example settings, integration tests and unit tests
=> feat: wallet scheme references from eudiw to haip

example/satosa/integration_test/main.py, pyeudiw/satosa/default/openid4vp_backend.py, pyeudiw/satosa/default/request_handler.py, pyeudiw/satosa/default/response_handler.py, pyeudiw/tests/satosa/test_backend.py, pyeudiw/tests/settings.py
Addressed the following:
- fixed issue #246 
- removed DPoP from integration test and backend invocation, as it is no longer required as per specs
- integration test and handlers now properly distinguish between response uri (invoked by wallet to send authorization response) and redirect uri (invoked after authentication is completed)
=> feat: stability of project

example/satosa/pyeudiw_backend.yaml, pyeudiw/satosa/default/openid4vp_backend.py, pyeudiw/satosa/schemas/config.py, pyeudiw/satosa/schemas/endpoint.py, pyeudiw/storage/schemas/storage.py
Closes #248 
Moreover, example has been updated to reflect the fact that request and response handler are configurable modules.
=> Fix: config schema validation

example/satosa/integration_test/commons.py, example/satosa/integration_test/cross_device_integration_test.py, example/satosa/integration_test/settings.py, example/satosa/templates/qr_code.html, pyeudiw/satosa/default/openid4vp_backend.py
This includes an initial implementation of cross device test, which closes #247 
This is a brief description of the proposed solution:
1. overall approach is similar to same device test
2. cookies and responses are updated to reflect the expectations of the cross device flow
3. after each authentication step in the flow, a second `request.Session` check(s) that the status endpoint yields the expected status code and message
Step 3 is non trivial as it requires obtaining somehow the status endpoint and its query parameters. This is done by parsing the Qr code page (pre authn endpoint), which is, frankly put, bad design... but I can't think of a better solution. Alternatives and proposals are welcomed
https://github.com/Zicchio/eudi-wallet-it-python/blob/bcd4593cf69070a649ba8573c407bc111a6e7 …
=> feat: cross device integration test

pyeudiw/tests/trust/default/test_direct_trust.py, pyeudiw/tests/trust/test_dynamic.py, pyeudiw/trust/default/__init__.py, pyeudiw/trust/default/direct_trust_sd_jwt_vc.py
With the proposed fix, direct trust sdjwt vc module can be used when httpc parameters are not defined. In that case, parameters are taken from environment variable, with default fallback value.
This fixes #279
=> fix: optional direct trust httpc params

example/satosa/integration_test/commons.py, pyeudiw/storage/db_engine.py, pyeudiw/storage/mongo_storage.py, pyeudiw/tests/satosa/test_backend.py, pyeudiw/tests/trust/test_dynamic.py, pyeudiw/trust/dynamic.py
closes #278
closes #282 by assuming that public jwk are always represented as array of jwk in trust evaluator and trust persistance layer.
=> fix: storage layer optionality

pyeudiw/satosa/default/request_handler.py, pyeudiw/tests/satosa/test_backend.py
This pull request updates Request Object `typ` claim in header to `oauth-authz-req+jwt`, as described in https://github.com/italia/eudi-wallet-it-docs/pull/460
=> chore: update request object typ

README.SATOSA.md, example/satosa/integration_test/same_device_integration_test.py, pyeudiw/satosa/default/openid4vp_backend.py
This pull requests closes #302 
The cross device flow now uses the same URL of the same device flow, and the URL value is the very same value that was previously yielded by the same device flow.
=> fix: qr code value

README.SATOSA.md, docs/TRUST.md, pyeudiw/tools/utils.py
Add env table to readme.md
The environment variable `PYEUDIW_LRU_CACHE_TTL` has been renamed to `PYEUDIW_LRU_CACHE_MAXSIZE` to accurately reflect its function, which defines the maximum capacity (`maxsize`) of the cache used by the `lru_cache` decorator. This update removes ambiguity in the naming and aligns the documentation with the actual behavior of the variable in the code.
=> docs: Add  table for environment variables in README.SATOSA.md

example/satosa/integration_test/commons.py, example/satosa/integration_test/cross_device_integration_test.py, example/satosa/integration_test/same_device_integration_test.py, example/satosa/pyeudiw_backend.yaml, pyeudiw/satosa/default/openid4vp_backend.py, pyeudiw/satosa/default/response_handler.py, pyeudiw/tests/satosa/test_backend.py, pyeudiw/tests/satosa/test_dynamic_backed.py, pyeudiw/tests/trust/handler/__init__.py, pyeudiw/tests/trust/handler/test_direct_trust.py, pyeudiw/tests/trust/handler/test_direct_trust_jar.py, pyeudiw/trust/dynamic.py, pyeudiw/trust/handler/_direct_trust_jwk.py, pyeudiw/trust/handler/direct_trust_jar.py, pyeudiw/trust/handler/direct_trust_sd_jwt_vc.py, pyeudiw/trust/handler/interface.py, pyeudiw/trust/interface.py
This PR includes the following:
1. extends the TrustHandler interface to allow the possibility to publish trust-framework defined endpoints
2. introduce a new trust evaluation mechanism, called DirectTrustJar, that extends DirectTrustSdJwtVc, to let RP publish its own signing keys
Notably, it does NOT update the former federation publication mechanism to use this new endpoint. This is because this task is not-trivial and probably requires a dedicated pull request.
With the exception above, this closes #312 and closes #296. When merged, a new issue should be opened to update federation.
Due to restrictions introduced by which endpoint can be exposed by a satosa backend module, integration tests require this modification to work https://github.com/italia/iam-proxy-italia/pull/177 . These …
=> feat: publish trust metadata endpoint

example/satosa/integration_test/same_device_integration_test.py, pyeudiw/openid4vp/authorization_response.py, pyeudiw/openid4vp/exceptions.py, pyeudiw/openid4vp/interface.py, pyeudiw/openid4vp/schemas/response.py, pyeudiw/satosa/default/response_handler.py, pyeudiw/tests/openid4vp/test_authorization_response.py
This PR closes #310
It introduces a new, very, very small asbtraction layer called `AuthorizationResponseParser` in the response handler that can process either direct_post responses or direct_post.jwt responses.
The current implementation is mean to be an extension of the current solution. In particular, like the current solution, the parsed content expects to find a `presentation_submission` and **is not ready to be extended with future DCQL support**.
When  DCQL will be supported, the interface definition `AuthorizationResponseParser` will likely have to be updated.
I decided to to preserve the "non compliance" with DCQL in order to isolate future code changes that will be result of that feature.
=> feat: support for direct_post (unencrypted) responses

pyeudiw/jwt/helper.py, pyeudiw/jwt/parse.py, pyeudiw/openid4vp/authorization_response.py, pyeudiw/openid4vp/interface.py, pyeudiw/openid4vp/vp_sd_jwt_vc.py, pyeudiw/satosa/default/response_handler.py, pyeudiw/tests/jwt/test_parse.py, pyeudiw/trust/handler/_direct_trust_jwk.py
This pull requests closes some minor issues and bugs, including:
1. this closes #346 by properly instatiating the decryptor with the software keys
2. this closes #345 by checking that `application/x-www-form-urlencoded` is included in the header, not strictly equal
3. this advances #342 by removing some buggy dead code with no side effects that was executed nonetheless (and failed http handlers when the unused dead code failed!!!)
4. this closes #341 by splitting error management between generic metadata fetch and jwk metadata fetch
5. EDIT: fixed broken indentation in this block of code https://github.com/italia/eudi-wallet-it-python/blob/486aa592d793e7a9922fe83430ce6b6558eefd45/pyeudiw/jwt/helper.py#L109-L129
=> fix: solved minor bugs

pyeudiw/tests/trust/handler/test_direct_trust.py, pyeudiw/trust/handler/_direct_trust_jwk.py
Fix #357 
FYI:
Commit [06798d4](https://github.com/italia/eudi-wallet-it-python/pull/374/commits/06798d43e8771eed8191dbdc972a502717cccf9f) resolves a bug where if no protocol is provided the the parsing results in a only path component with the consequent return value, assuming that the url component is 4d2d5e12-4123-475f-8fa9-807d46df324f.issuer.it, in:
/.well-known/jwt-vc-issuer4d2d5e12-4123-475f-8fa9-807d46df324f.issuer.it
I've added https as fallback for this reason.
=> Non conformant url requests

pyeudiw/openid4vp/authorization_response.py, pyeudiw/tests/openid4vp/test_authorization_response.py
This closes #383 
Note that for retrocompatibility purposes, in this pull request both string and JSON string are accepted as representation format for vp_token in direct_post flow.
=> feat: direct_post input normalization

pyeudiw/tests/openid4vp/test_vp_sd_jwt_vc.py
This PR fixes a unit test that was accidentally broken during some merge operations and was not naught by CI/CD pipeline due to the fact that the pipeline does not re-run between merges.
=> Fix broken unit test

example/satosa/integration_test/commons.py, example/satosa/integration_test/cross_device_integration_test.py, example/satosa/integration_test/same_device_integration_test.py, example/satosa/integration_test/same_device_integration_test_duckle.py, example/satosa/integration_test/testconfig/potential/wp2uc1/userdenies/pyeudiw_backend.yaml, example/satosa/integration_test/user_denies_end_to_end_test.py, example/satosa/pyeudiw_backend.yaml, example/satosa/static/css/style.css, example/satosa/templates/authorization_error.html, pyeudiw/openid4vp/schemas/response.py, pyeudiw/satosa/default/openid4vp_backend.py, pyeudiw/satosa/default/response_handler.py, pyeudiw/satosa/utils/html_template.py, pyeudiw/tests/satosa/templates/authorization_error.html, pyeudiw/tests/settings.py
This PR is **PARTIAL** attempt at dealing with #378. The goal of this PR is to provide a **minimal** working error error management for cases when the user denies the authentication request.
Implementation details as follows in scenarios where the wallet sends an authorization error response.
1. The status endpoint was updated to return 401 errors. As a consequence, the page with a QR code and polling javascript will update accordingly (relevant for cross device flow).
2. The redirect_uri leads to a generic error page¹ signaling that the authentication was canceled or failed (relevant for same device flow).
3. Suggestions proposed here https://github.com/italia/eudi-wallet-it-python/issues/378#issuecomment-2790346402 were not taken into account
A new integration test was added to test …
=> feat: authorization error response

pyeudiw/jwk/parse.py, pyeudiw/jwt/helper.py, pyeudiw/jwt/jws_helper.py, pyeudiw/openid4vp/presentation_submission/__init__.py, pyeudiw/satosa/default/request_handler.py, pyeudiw/tests/jwt/test_helper.py, pyeudiw/tests/jwt/test_sign_verify.py, pyeudiw/tests/satosa/test_backend.py, pyeudiw/x509/verify.py
This PR closes #423 and in particular does the following:
1. when signing a jwt with a set of available keys and header x5c is in the token, use a key that matches the x5c header (refactored from `request_handler.py` to `jws_helper.JWSHelper`)
2. when signing a token, a consistency double check is performed to verify that the signing key indeed matches possible "kid" header and "x5c" header (when present in both the key and the header).
3. some minor fixes here and there discovered when working on issue 423.
@peppelinux commits can be squashed
=> feat: refactor of jwt key selection for x5c

pyeudiw/satosa/frontends/openid4vci/endpoints/authorization_endpoint.py, pyeudiw/satosa/frontends/openid4vci/endpoints/base_credential_endpoint.py, pyeudiw/satosa/frontends/openid4vci/endpoints/credential_offer_qrcode_endpoint.py, pyeudiw/satosa/frontends/openid4vci/endpoints/nonce_endpoint.py, pyeudiw/satosa/frontends/openid4vci/endpoints/pushed_authorization_request_endpoint.py, pyeudiw/satosa/frontends/openid4vci/endpoints/token_endpoint.py, pyeudiw/satosa/frontends/openid4vci/models/par_request.py, pyeudiw/satosa/frontends/openid4vci/openid4vci.py, pyeudiw/satosa/frontends/openid4vci/storage/engine.py, pyeudiw/satosa/frontends/openid4vci/storage/entity.py, pyeudiw/satosa/frontends/openid4vci/storage/openid4vci_storage.py, pyeudiw/tests/satosa/frontends/openid4vci/models/test_par_request.py, pyeudiw/tools/date.py
This PR removes the work done in #484 in favor on an approach more dynamic.
As described in in the PAR [section in Openid4vci](https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#name-pushed-authorization-reques) in the body of the request are included only the fields are: scope, response_type, client_id, code_challenge, code_challenge_method, state, redirect_uri.
For this reason it can't be mapped 1:1 with an IT Wallet request because the signed jwt has more fields that are validated like exp or jti.
To enable the interoperability between IT Wallet and the classical Openid4VCI the PAR endpoints checks that the body contains a request parameter.
If present, and the signed_par_request is true or both, it validate and decode the body of JWT and does all …
=> [Interoperability] Oauth2 par request
